version: "3.1"
services:
  ping-machine-db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ping-machine
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
